apiVersion: orchestrator.entur.io/apps/v1
kind: GoogleCloudFirebaseApplication
metadata:
  id: statusber
  displayName: Statusskjerm Produkt
  name: statusskjerm-produkt
  owner: team-produkt
spec:
  environments: [prd]
  repositories: [statusskjerm-produkt]
